services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - "/home/docker-data/ollama:/root/.ollama"
    environment:
      - OLLAMA_CONTEXT_LENGTH=128000
      - OLLAMA_API_KEY="${CODER_ACCESS_URL}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - "/home/docker-data/open-webui:/app/backend/data"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
      - searxng

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "/home/docker-data/searxng:/etc/searxng"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

networks:
  default:
    name: llm_network
