services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - "/home/docker-data/bitwarden:/data"
    ports:
      - "32771:80"

  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    volumes:
      - "/home/docker-data/gitea:/data:rw"
    ports:
      - "3010:3000"
      - "2022:22"

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - "/home/docker-data/homebridge:/homebridge:rw"
    network_mode: host

  stashapp:
    container_name: stashapp
    image: stashapp/stash:latest
    restart: always
    volumes:
      - "/home/docker-data/stash/blobs:/blobs"
      - "/home/docker-data/stash/cache:/cache"
      - "/home/docker-data/stash/config:/root/.stash"
      - "/home/docker-data/stash/data:/data"
      - "/home/docker-data/stash/generated:/generated"
      - "/home/docker-data/stash/metadata:/metadata"
    ports:
      - "9999:9999"

networks:
  default:
    name: utilities_network